### ISSUE TITLE
Add the ability to output package list to a file.

### ISSUE THREAD

**Issue by MehdiChinoune** [jeremyd2019/package-grokker#11]

**Comment by jeremyd2019** [comment]
do you mean just sending the normal output to a file? why not just redirect stdout (well, package-update-check.py also outputs the set of changed symbols/dlls in a GHA group, mostly for debugging/verifying what the script is doing... maybe that should be behind a `-v/--verbose` flag?)

**Comment by MehdiChinoune** [comment]
> well, package-update-check.py also outputs the set of changed symbols/dlls
 
Yes, That's the issue.
