### ISSUE TITLE
AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_IMPORT'

### ISSUE THREAD

**Issue by lazka** [jeremyd2019/package-grokker#18]
```
Traceback (most recent call last):
  File "/home/runner/work/_actions/jeremyd2019/package-grokker/main/grokkermod.py", line 71, in __call__
    for entry in pe.DIRECTORY_ENTRY_IMPORT:
AttributeError: 'PE' object has no attribute 'DIRECTORY_ENTRY_IMPORT'
```

https://github.com/msys2/MINGW-packages/actions/runs/6988233339/job/19015883798?pr=19193

**Comment by jeremyd2019** [comment]
It looks like something in `mingw-w64-clang-x86_64-mypy` is not being parsed correctly by pefile.  The only "legitimate" reason for that would be a PE file *without* an import directory, but my understanding was that possibility was basically academic - you'd need at least *some* imports to interact with the system *at all* (perhaps unless you were trying to make an intentionally inscrutable binary, but we're not analyzing malware here...).  More likely is that something in pefile went sideways.

**Comment by lazka** [comment]
yeah, mypyc.exe is broken in general:

```
mypyc
-bash: /clang64/bin/mypyc: cannot execute binary file: Exec format error
```

**Comment by lazka** [comment]
uh, ok: https://github.com/msys2/MINGW-packages/commit/27ef8231ca8dbd75a87f46f7d7dca920c4987c26

**Comment by lazka** [comment]
Fixed by https://github.com/msys2/MINGW-packages/pull/19207

Feel free to close this

**Comment by jeremyd2019** [comment]
OK, I guess expected behavior that it would throw/error out on a corrupt binary.
